### ISSUE TITLE
Homebrew doesn't upgrade kraken properly?

### ISSUE THREAD

**Issue by samba** [samsung-cnct/homebrew-kraken#21]
When attempting to upgrade, Homebrew doesn't seem to find a newer release, rather it seemed to believe the installed version was current. 

Previously installed by homebrew:
`1.1.2-stable+git.sha.b5e3ed0c80f79784c855a0e2575ee2b5561a9203`

Actual current version:
`1.2.2-stable+git.sha.c183b3351a381786a22cb948bdfc2f7dfdcc07f2`

Even after removing the prior version, it didn't recognize the version upgrade, but did warn of a hash mismatch:

```
$ brew remove kraken
Uninstalling /usr/local/Cellar/kraken/64... (3 files, 11.3MB)
$ brew install kraken
==> Installing kraken from samsung-cnct/k2cli
==> Downloading https://github.com/samsung-cnct/kraken/releases/download/1.2.2/kraken_1.2.2_darwin_amd64.tar.gz
Already downloaded: ${HOME}/Library/Caches/Homebrew/kraken-64.tar.gz
Error: SHA256 mismatch
Expected: 7c5d6aec244384fbb9d43ee212ae950fca9ed6e20254159eed8a485cc0e7fe5c
Actual: 5f9f83ac3dfcf37677bc1d575126a6f4aeca0ea7b6855b16823e3c0a62b319f4
Archive: ${HOME}/Library/Caches/Homebrew/kraken-64.tar.gz
```

Workaround:
- `brew remove kraken`
- `rm -f ${HOME}/Library/Caches/Homebrew/kraken-64.tar.gz` 
- `brew install kraken`

**Comment by philoserf** [comment]
alternative workaround

```shell
brew remove kraken
brew cleanup -s
brew install kraken
```

**Comment by coffeepac** [comment]
p1
